.TL
this ufjjgu title tag
.AU
Luke Smith
.AI
authir insyitution
.AB
this is an abs tract
.AE
.PP
paragraph tag
.NH
second Section
.NH 2
subsection on 2nd level
.NH 2
another subsection
.PP
I jist want this
word
.B "bold to be bold"
yeah.
.I "itellic text"
.BI "bold itelic text"
.RS
.PP
I jist want this
word
.B "bold to be bold"
yeah.
.I "itellic text"
.BI "bold itelic text"
.RE
.PP
I jist want this
word
.B "bold to be bold"
yeah.
.I "itellic text"
.BI "bold itelic text"
